function CodeDefine() { 
this.def = new Array();
this.def["CartesianImpedance_Task_xnrm2"] = {file: "CartesianImpedance_Task_cpp.html",line:22,type:"fcn"};
this.def["CartesianImpedanc_rt_hypotd_snf"] = {file: "CartesianImpedance_Task_cpp.html",line:54,type:"fcn"};
this.def["CartesianImpedance_Task_xgerc"] = {file: "CartesianImpedance_Task_cpp.html",line:75,type:"fcn"};
this.def["CartesianImpedance_Task_xgehrd"] = {file: "CartesianImpedance_Task_cpp.html",line:106,type:"fcn"};
this.def["CartesianImpedance_Task_xzlanhs"] = {file: "CartesianImpedance_Task_cpp.html",line:345,type:"fcn"};
this.def["CartesianImpedance_Ta_xzlartg_m"] = {file: "CartesianImpedance_Task_cpp.html",line:407,type:"fcn"};
this.def["CartesianImpedance_Task_xzlartg"] = {file: "CartesianImpedance_Task_cpp.html",line:520,type:"fcn"};
this.def["CartesianImpedance_Task_xzhgeqz"] = {file: "CartesianImpedance_Task_cpp.html",line:659,type:"fcn"};
this.def["CartesianImpedance_Task_xztgevc"] = {file: "CartesianImpedance_Task_cpp.html",line:1171,type:"fcn"};
this.def["CartesianImpedance_Task_xzggev"] = {file: "CartesianImpedance_Task_cpp.html",line:1491,type:"fcn"};
this.def["CartesianImpedance_Task_xdlanv2"] = {file: "CartesianImpedance_Task_cpp.html",line:1978,type:"fcn"};
this.def["CartesianImpedance_Task_xrot"] = {file: "CartesianImpedance_Task_cpp.html",line:2123,type:"fcn"};
this.def["CartesianImpedance_Task_xnrm2_p"] = {file: "CartesianImpedance_Task_cpp.html",line:2142,type:"fcn"};
this.def["CartesianImpedance_Ta_xzlarfg_d"] = {file: "CartesianImpedance_Task_cpp.html",line:2179,type:"fcn"};
this.def["CartesianImpedance_Task_xhseqr"] = {file: "CartesianImpedance_Task_cpp.html",line:2238,type:"fcn"};
this.def["CartesianImpedance_Task_eig"] = {file: "CartesianImpedance_Task_cpp.html",line:2612,type:"fcn"};
this.def["CoordinateTransformationC_Start"] = {file: "CartesianImpedance_Task_cpp.html",line:3202,type:"fcn"};
this.def["CoordinateTransformationConvers"] = {file: "CartesianImpedance_Task_cpp.html",line:3215,type:"fcn"};
this.def["CartesianImpedance_anyNonFinite"] = {file: "CartesianImpedance_Task_cpp.html",line:3302,type:"fcn"};
this.def["CartesianImpedance_Task_xnrm2_g"] = {file: "CartesianImpedance_Task_cpp.html",line:3318,type:"fcn"};
this.def["CartesianImpedance_Tas_xnrm2_gh"] = {file: "CartesianImpedance_Task_cpp.html",line:3348,type:"fcn"};
this.def["CartesianImpedance_Tas_xaxpy_ag"] = {file: "CartesianImpedance_Task_cpp.html",line:3376,type:"fcn"};
this.def["CartesianImpedance_Task_xaxpy_a"] = {file: "CartesianImpedance_Task_cpp.html",line:3393,type:"fcn"};
this.def["CartesianImpedance_Task_xdotc"] = {file: "CartesianImpedance_Task_cpp.html",line:3410,type:"fcn"};
this.def["CartesianImpedance_Task_xaxpy"] = {file: "CartesianImpedance_Task_cpp.html",line:3430,type:"fcn"};
this.def["CartesianImpedance_Task_xscal"] = {file: "CartesianImpedance_Task_cpp.html",line:3447,type:"fcn"};
this.def["CartesianImpedance_Task_xswap"] = {file: "CartesianImpedance_Task_cpp.html",line:3458,type:"fcn"};
this.def["CartesianImpedance_Task_xrotg"] = {file: "CartesianImpedance_Task_cpp.html",line:3474,type:"fcn"};
this.def["CartesianImpedance_Task_xrot_i"] = {file: "CartesianImpedance_Task_cpp.html",line:3518,type:"fcn"};
this.def["CartesianImpedance_Task_svd_b"] = {file: "CartesianImpedance_Task_cpp.html",line:3536,type:"fcn"};
this.def["CartesianImpedance_Task_svd_ij"] = {file: "CartesianImpedance_Task_cpp.html",line:4149,type:"fcn"};
this.def["CartesianImpedance_Task_svd"] = {file: "CartesianImpedance_Task_cpp.html",line:4760,type:"fcn"};
this.def["step"] = {file: "CartesianImpedance_Task_cpp.html",line:4800,type:"fcn"};
this.def["initialize"] = {file: "CartesianImpedance_Task_cpp.html",line:5895,type:"fcn"};
this.def["terminate"] = {file: "CartesianImpedance_Task_cpp.html",line:8957,type:"fcn"};
this.def["B_CoordinateTransformationCon_T"] = {file: "CartesianImpedance_Task_h.html",line:197,type:"type"};
this.def["DW_CoordinateTransformationCo_T"] = {file: "CartesianImpedance_Task_h.html",line:204,type:"type"};
this.def["B_CartesianImpedance_Task_T"] = {file: "CartesianImpedance_Task_h.html",line:362,type:"type"};
this.def["DW_CartesianImpedance_Task_T"] = {file: "CartesianImpedance_Task_h.html",line:426,type:"type"};
this.def["ConstB_CartesianImpedance_Tas_T"] = {file: "CartesianImpedance_Task_h.html",line:431,type:"type"};
this.def["initialize"] = {file: "CartesianImpedance_Task_h.html",line:445,type:"fcn"};
this.def["robotics_slcore_internal_bloc_T"] = {file: "CartesianImpedance_Task_types_h.html",line:27,type:"type"};
this.def["RT_MODEL_CartesianImpedance_T_T"] = {file: "CartesianImpedance_Task_types_h.html",line:32,type:"type"};
this.def["CartesianImpedance_Task_ConstB"] = {file: "CartesianImpedance_Task_data_cpp.html",line:23,type:"var"};
this.def["rtGetInf"] = {file: "rtGetInf_cpp.html",line:31,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_cpp.html",line:55,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_cpp.html",line:66,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_cpp.html",line:90,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_cpp.html",line:31,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_cpp.html",line:55,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_cpp.html",line:30,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_cpp.html",line:31,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_cpp.html",line:32,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_cpp.html",line:33,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_cpp.html",line:34,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_cpp.html",line:35,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_cpp.html",line:43,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_cpp.html",line:55,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_cpp.html",line:61,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_cpp.html",line:67,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_cpp.html",line:90,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:45,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:52,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:59,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:51,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:52,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:55,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:56,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:57,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:58,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:72,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:82,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:87,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:92,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:99,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:106,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:113,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:120,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:127,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:134,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:152,type:"type"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "/";
var isPC = false;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["CartesianImpedance_Task_cpp.html"] = "../CartesianImpedance_Task.cpp";
	this.html2Root["CartesianImpedance_Task_cpp.html"] = "CartesianImpedance_Task_cpp.html";
	this.html2SrcPath["CartesianImpedance_Task_h.html"] = "../CartesianImpedance_Task.h";
	this.html2Root["CartesianImpedance_Task_h.html"] = "CartesianImpedance_Task_h.html";
	this.html2SrcPath["CartesianImpedance_Task_private_h.html"] = "../CartesianImpedance_Task_private.h";
	this.html2Root["CartesianImpedance_Task_private_h.html"] = "CartesianImpedance_Task_private_h.html";
	this.html2SrcPath["CartesianImpedance_Task_types_h.html"] = "../CartesianImpedance_Task_types.h";
	this.html2Root["CartesianImpedance_Task_types_h.html"] = "CartesianImpedance_Task_types_h.html";
	this.html2SrcPath["CartesianImpedance_Task_data_cpp.html"] = "../CartesianImpedance_Task_data.cpp";
	this.html2Root["CartesianImpedance_Task_data_cpp.html"] = "CartesianImpedance_Task_data_cpp.html";
	this.html2SrcPath["rtGetInf_cpp.html"] = "../rtGetInf.cpp";
	this.html2Root["rtGetInf_cpp.html"] = "rtGetInf_cpp.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_cpp.html"] = "../rtGetNaN.cpp";
	this.html2Root["rtGetNaN_cpp.html"] = "rtGetNaN_cpp.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_nonfinite_cpp.html"] = "../rt_nonfinite.cpp";
	this.html2Root["rt_nonfinite_cpp.html"] = "rt_nonfinite_cpp.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"CartesianImpedance_Task_cpp.html","CartesianImpedance_Task_h.html","CartesianImpedance_Task_private_h.html","CartesianImpedance_Task_types_h.html","CartesianImpedance_Task_data_cpp.html","rtGetInf_cpp.html","rtGetInf_h.html","rtGetNaN_cpp.html","rtGetNaN_h.html","rt_nonfinite_cpp.html","rt_nonfinite_h.html","rtwtypes_h.html","rtmodel_h.html"];
